// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RegistrationManagementSystem.API.Data;

#nullable disable

namespace RegistrationManagementSystem.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521100711_SeedAdminUser")]
    partial class SeedAdminUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ahmedabad",
                            StateId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Surat",
                            StateId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Vadodara",
                            StateId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Rajkot",
                            StateId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Una",
                            StateId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Mumbai",
                            StateId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Pune",
                            StateId = 2
                        },
                        new
                        {
                            Id = 8,
                            Name = "Nagpur",
                            StateId = 2
                        },
                        new
                        {
                            Id = 9,
                            Name = "Jaipur",
                            StateId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jodhpur",
                            StateId = 3
                        },
                        new
                        {
                            Id = 11,
                            Name = "New Delhi",
                            StateId = 4
                        },
                        new
                        {
                            Id = 12,
                            Name = "Dwarka",
                            StateId = 4
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bangalore",
                            StateId = 5
                        },
                        new
                        {
                            Id = 14,
                            Name = "Mysore",
                            StateId = 5
                        });
                });

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hobbies")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("StateId");

                    b.HasIndex("UserId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gujarat"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maharashtra"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rajasthan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Delhi"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Karnataka"
                        });
                });

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Admin",
                            PasswordHash = "$2a$11$Tg4MvNMoGGsupfh9S3X5XOqfHmFBBBnGRFp5yXqbTi6GK9JdFgW2i",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.UserDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("RegistrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.City", b =>
                {
                    b.HasOne("RegistrationManagementSystem.API.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.Registration", b =>
                {
                    b.HasOne("RegistrationManagementSystem.API.Models.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RegistrationManagementSystem.API.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RegistrationManagementSystem.API.Models.User", "User")
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("State");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.UserDocument", b =>
                {
                    b.HasOne("RegistrationManagementSystem.API.Models.Registration", "Registration")
                        .WithMany("Documents")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.Registration", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.State", b =>
                {
                    b.Navigation("Cities");
                });

            modelBuilder.Entity("RegistrationManagementSystem.API.Models.User", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
